- hosts: idn
  become: yes
  vars: 
    - image: audhie89/web_nginx
  tasks:
    - name: pull image 
      docker_image: 
        name: "{{ image }}"
        state: present 
        force: yes


    - name: create containers
      docker_container:
         name: docker-ansible 
         image: "{{ image }}"
         state: started 
         published_ports:
           - 1010:80
         recreate: yes
